version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - '8080:8080'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
      - POSTGRES_USER=app
      - POSTGRES_DB=app


